version: "3"
services:
  drf-vue-sample:
    build:
      context: .
      args:
        WORKDIR: /workspace
    volumes:
      - .:/workspace
      - /workspace/frontend/node_modules
    image: workspace-img
    container_name: workspace-cnt
    ports:
      # Liver Server
      - "18080:18080"
      - "18000:18000"
